version: '3'
services:
  api:
    build: .
    container_name: order-api
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment: 
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - /data/db